export default function Privacy() {

    // Scroll to top when page is loaded
    window.scrollTo({ top: 0, behavior: 'smooth' });

    return (

        <div className="bg-white dark:bg-black min-h-screen px-4 sm:px-8 md:px-16 pb-16 pt-28 text-black dark:text-gray-300">

            <div className="max-w-5xl mx-auto space-y-8">

                <div className="text-center mb-12">
                    <h1 className="text-4xl font-bold mb-2">Privacy Policy</h1>
                    <p className="text-sm text-gray-500 dark:text-gray-400">Last updated: November 28, 2025</p>
                </div>

                <section className="mb-10">
                    <div className="space-y-4">
                        <p>
                            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                        </p>
                        <p>
                            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                        </p>
                    </div>
                </section>

                <section className="mb-10">
                    <h2 className="text-2xl font-bold mb-4 border-b pb-2 dark:border-gray-700">Interpretation and Definitions</h2>
                    <div className="space-y-4">
                        <h3 className="text-xl font-semibold mt-4">Interpretation</h3>
                        <p>
                            The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                        </p>

                        <h3 className="text-xl font-semibold mt-4">Definitions</h3>
                        <p>For the purposes of this Privacy Policy:</p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                            <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                            <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Exbot, a subsidiary of Exmedia, which provides WhatsApp Cloud API, WhatsApp Automation, and Chatbot services.</li>
                            <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                            <li><strong>Country</strong> refers to: Kerala, India.</li>
                            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                            <li><strong>Service</strong> refers to the Website and all services provided by Exbot, including the WhatsApp Cloud API, WhatsApp Automation, and Chatbot systems.</li>
                            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. This includes third-party companies like Meta Platforms, Inc. (WhatsApp) required to facilitate the core functionality of the Service.</li>
                            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                            <li><strong>Website</strong> refers to exbot, accessible from <a href="https://www.exbot.in" className="underline text-blue-500 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300">www.exbot.in</a>.</li>
                            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                        </ul>
                    </div>
                </section>

                <section className="mb-10">
                    <h2 className="text-2xl font-bold mb-4 border-b pb-2 dark:border-gray-700">Collecting and Using Your Personal Data</h2>
                    <div className="space-y-4">
                        <h3 className="text-xl font-semibold mt-4">Types of Data Collected</h3>

                        <h4 className="text-lg font-semibold mt-4">Personal Data</h4>
                        <p>
                            While using Our Service, and particularly for the setup and configuration of the exbot WhatsApp API and Chatbot system, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                        </p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>Email address</li>
                            <li>Phone number (Essential for WhatsApp API services)</li>
                            <li>First name and last name</li>
                            <li>Address</li>
                            <li>Business details (e.g., company name, website, business vertical)</li>
                            <li>Social media</li>
                            <li>e-commerce platforms</li>
                        </ul>
                        <p>
                            <strong>Note on Data Necessity:</strong> We collect Email ID, Phone Number, Address, and Business Details specifically to meet the requirements set by Meta Platforms, Inc. for configuring and operating Your WhatsApp business number within our system, ensuring compliance and service functionality.
                        </p>

                        <h4 className="text-lg font-semibold mt-4">Usage Data</h4>
                        <p>
                            Usage Data is collected automatically when using the Service.
                        </p>
                        <p>
                            Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                        </p>
                    </div>
                </section>

                <section className="mb-10">
                    <h2 className="text-2xl font-bold mb-4 border-b pb-2 dark:border-gray-700">Tracking Technologies and Cookies</h2>
                    <div className="space-y-4">
                        <p>
                            We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
                        </p>
                    </div>
                </section>

                <section className="mb-10">
                    <h2 className="text-2xl font-bold mb-4 border-b pb-2 dark:border-gray-700">Use of Your Personal Data</h2>
                    <div className="space-y-4">
                        <p>The Company may use Personal Data for the following purposes:</p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li><strong>To provide and maintain our Service:</strong> Including to monitor the usage of our Service and to ensure the proper functioning of the WhatsApp API and Chatbot services.</li>
                            <li><strong>To manage Your Account:</strong> To manage Your registration as a user of the Service and fulfill the contract for automation services.</li>
                            <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as push notifications regarding updates or informative communications related to the functionalities, products or contracted services.</li>
                            <li><strong>For Business Transfers and Other Purposes:</strong> For data analysis, identifying usage trends, and evaluating/improving our Service, products, and marketing.</li>
                        </ul>
                    </div>
                </section>

                <section className="mb-10">
                    <h2 className="text-2xl font-bold mb-4 border-b pb-2 dark:border-gray-700">Retention of Your Personal Data</h2>
                    <div className="space-y-4">
                        <p>
                            The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements.
                        </p>
                    </div>
                </section>

                <section className="mb-10">
                    <h2 className="text-2xl font-bold mb-4 border-b pb-2 dark:border-gray-700">Transfer of Your Personal Data</h2>
                    <div className="space-y-4">
                        <p>
                            Your information, including Personal Data, may be transferred to and maintained on computers located outside of Your jurisdiction where the data protection laws may differ.
                        </p>
                        <p>
                            Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer. The Company will take all reasonable steps to ensure Your data is treated securely.
                        </p>
                    </div>
                </section>

                <section className="mb-10">
                    <h2 className="text-2xl font-bold mb-4 border-b pb-2 dark:border-gray-700">Delete Your Personal Data</h2>
                    <div className="space-y-4">
                        <p>
                            You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us. We may need to retain certain information when we have a legal obligation or lawful basis to do so.
                        </p>
                    </div>
                </section>

                <section className="mb-10">
                    <h2 className="text-2xl font-bold mb-4 border-b pb-2 dark:border-gray-700">Disclosure of Your Personal Data</h2>
                    <div className="space-y-4">
                        <h3 className="text-xl font-semibold mt-4">Business Transactions</h3>
                        <p>
                            If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred.
                        </p>

                        <h3 className="text-xl font-semibold mt-4">Law enforcement and Other legal requirements</h3>
                        <p>
                            The Company may disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities, or where necessary to:
                        </p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>Comply with a legal obligation</li>
                            <li>Protect and defend the rights or property of the Company</li>
                            <li>Protect the personal safety of Users of the Service or the public</li>
                            <li>Protect against legal liability</li>
                        </ul>
                    </div>
                </section>

                <section className="mb-10">
                    <h2 className="text-2xl font-bold mb-4 border-b pb-2 dark:border-gray-700">Detailed Information on the Processing of Your Personal Data</h2>
                    <div className="space-y-4">
                        <p>
                            The Service Providers We use may have access to Your Personal Data. These third-party vendors collect, store, use, process and transfer information about Your activity on Our Service in accordance with their Privacy Policies.
                        </p>

                        <h3 className="text-xl font-semibold mt-4">Core Service Provider (WhatsApp API)</h3>
                        <p>
                            <strong>Meta Platforms, Inc. (WhatsApp):</strong> As the Service revolves around the WhatsApp Cloud API, customer data (including phone numbers and business details) is processed by Meta Platforms, Inc. as a necessary component to deliver the Service. The information processed by Meta Platforms, Inc. is governed by the Privacy Policy of Meta.
                        </p>
                    </div>
                </section>

                <section className="mb-10">
                    <h2 className="text-2xl font-bold mb-4 border-b pb-2 dark:border-gray-700">Children's Privacy</h2>
                    <div className="space-y-4">
                        <p>
                            Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.
                        </p>
                    </div>
                </section>

                <section className="mb-10">
                    <h2 className="text-2xl font-bold mb-4 border-b pb-2 dark:border-gray-700">Links to Other Websites</h2>
                    <div className="space-y-4">
                        <p>
                            Our Service may contain links to other websites that are not operated by Us. We strongly advise You to review the Privacy Policy of every site You visit. We assume no responsibility for the content, privacy policies or practices of any third-party sites or services.
                        </p>
                    </div>
                </section>

                <section className="mb-10">
                    <h2 className="text-2xl font-bold mb-4 border-b pb-2 dark:border-gray-700">Changes to this Privacy Policy</h2>
                    <div className="space-y-4">
                        <p>
                            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date.
                        </p>
                    </div>
                </section>

                <section className="mb-10">
                    <h2 className="text-2xl font-bold mb-4 border-b pb-2 dark:border-gray-700">Contact Us</h2>
                    <div className="space-y-4">
                        <p>If you have any questions about this Privacy Policy, You can contact us:</p>
                        <p>
                            By email: <a href="mailto:care@exbot.in" className="underline text-blue-500 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300">care@exbot.in</a>
                        </p>
                    </div>
                </section>
            </div>
        </div>
    );
}